application: cienciascognitivas
version: 1
runtime: python
api_version: 1

handlers:
- url: /style
  static_dir: style
  
- url: /imagenes
  static_dir: imagenes

- url: /scripts
  static_dir: scripts

- url: /games.*
  script: games.py

- url: /memoria.*
  script: memoria.py
  
- url: /resultados
  script: resultados.py
  # TODO: Falta hacer la pagina de resultados

- url: /.*
  script: main.py
