application: cienciascognitivas
version: 1
runtime: python
api_version: 1

handlers:
- url: /style
  static_dir: Style

- url: /imagenes
  static_dir: imagenes

- url: /scripts
  static_dir: scripts

- url: /games.*
  script: games.py

- url: /memoria.*
  script: memoria.py

- url: /.*
  script: main.py
